; OpenSnowstorm Options
; Game Speed: 1=Normal, 2=Fast, 4=Very Fast, etc.
game_speed=4
volume=50

; Hotkeys (ASCII characters)
hotkey_stop=s
hotkey_hold=h
hotkey_attack=a
hotkey_patrol=t
hotkey_build=b
hotkey_cloak=c
hotkey_burrow=b
hotkey_siege=g
hotkey_stim=i
hotkey_unload=l
hotkey_lift=l
hotkey_return_cargo=r
hotkey_merge=m
hotkey_cancel=x
